<?php

/**
 * @file
 * Main TwerkList Core file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function twerklist_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['node_related'] = array(
    'label' => t('Node Related'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['node_related'] = array(
    'label' => t('Node Related'),
    'custom settings' => TRUE,
  );
}

/**
 * Implent hook_node_view()
 */
function twerklist_core_node_view($node, $view_mode, $langcode) {

  switch ($view_mode) {
    case 'teaser':
    case 'node_related':

      // Link the image to related content.
      // @todo There should be a better way?!
      if (!empty($node->content['field_video_single'][0]['file'])) {
        $the_image = $node->content['field_video_single'][0]['file'];

        $element = array(
          '#theme' => 'link',
          '#path' => 'node/' . $node->nid,
          '#text' => drupal_render($the_image),
          '#options' => array(
            'attributes' => array(),
            'html' => TRUE,
          ),
        );

        $node->content['field_video_single'][0]['file'] = $element;
      }

      break;

    default:
      break;
  }
}

/**
 * Implement hook_css_alter
 */
function twerklist_core_css_alter(&$css) {
  // Get rid of thumbs-up-down.css file.
  unset($css[drupal_get_path('module', 'rate') . '/templates/thumbs-up-down/thumbs-up-down.css']);
}

function twerklist_core_preprocess_html(&$vars) {

  $bing_tag = array(
    '#tag' => 'meta', // The #tag is the html tag - <link />
    '#attributes' => array(
      'name' => 'msvalidate.01',
      'content' => 'CD556FD9720B0D6A617B1DF54833ECF7',
    ),
  );

  drupal_add_html_head($bing_tag, 'bing_search_index');
}

/**
 * Implements hook_field_extra_fields().
 */
function twerklist_core_field_extra_fields() {
  
    $extra['node']['article'] = array(
      'display' => array(
        'article_bottom_info' => array(
          'label' => t('Bottom Info'),
          'description' => t('Article Bottom Info'),
          'weight' => 0,
        ),
      ),
    );

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function twerklist_core_entity_view($entity, $type, $view_mode, $langcode) {
  $node_types = array('article');

  if (in_array($entity->type, $node_types) && $view_mode == 'full') {
    $entity->content['article_bottom_info'] = array(
      '#markup' => _twerklist_core_get_bottom_info($entity),
      '#prefix' => '<div class="article_bottominfo_extra">',
      '#suffix' => '</div>',
    );
  }
}


/**
 * @todo Double call, fix it.
 */
function _twerklist_core_get_bottom_info($entity) {  
  $fields = array('body', 'field_music_in_video');
  $content = array();
  
  foreach ($fields as $field_name) {
    $field_data = field_get_items('node', $entity, $field_name);
    if (is_array($field_data)) {
      $content[] = field_view_field('node', $entity, $field_name, 'full');
    }
  }
  
  return render($content);
}