<?php

/**
 * @file
 * Main TwerkList Core file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function twerklist_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['node_related'] = array(
    'label' => t('Node Related'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['node_related'] = array(
    'label' => t('Node Related'),
    'custom settings' => TRUE,
  );
}

/**
 * Implent hook_node_view()
 */
function twerklist_core_node_view($node, $view_mode, $langcode) {

  switch ($view_mode) {
    case 'teaser':
    case 'node_related':

      // Link the image to related content.
      // @todo There should be a better way?!
      if (!empty($node->content['field_video_single'][0]['file'])) {
        $the_image = $node->content['field_video_single'][0]['file'];

        $element = array(
          '#theme' => 'link',
          '#path' => 'node/' . $node->nid,
          '#text' => drupal_render($the_image),
          '#options' => array(
            'attributes' => array(),
            'html' => TRUE,
          ),
        );

        $node->content['field_video_single'][0]['file'] = $element;
      }

      break;

    default:
      break;
  }
}

/**
 * Implement hook_css_alter
 */
function twerklist_core_css_alter(&$css) {
  // Get rif of thumbs-up-down.css file.
  unset($css[drupal_get_path('module', 'rate') . '/templates/thumbs-up-down/thumbs-up-down.css']);
}

function twerklist_core_preprocess_html(&$vars) {

  $element = array(
    '#tag' => 'meta', // The #tag is the html tag - <link />
    '#attributes' => array(
      'name' => 'msvalidate.01',
      'content' => 'CD556FD9720B0D6A617B1DF54833ECF7',
    ),
  );

  drupal_add_html_head($element, 'bing_search_index');
}
